# Generated by Django 5.2.4 on 2025-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
