# Generated by Django 5.2.4 on 2025-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, choices=[('cakes', 'cakes'), ('pastries', 'pastries'), ('fried', 'fried'), ('nimko', 'nimko'), ('drinks', 'drinks'), ('sweets', 'sweets')], max_length=255, null=True),
        ),
    ]
