# Generated by Django 5.2.4 on 2025-08-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
