# Generated by Django 5.2.4 on 2025-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invoiceitem_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
